version: "3"
services:
  config-service:
    image: davimonteiro/config-service
    ports:
    - 8888:8888
  hystrix-dashboard:
    image: davimonteiro/hystrix-dashboard
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
    ports:
    - 6161:6161
    links:
    - config-service
  discovery-service:
    image: davimonteiro/discovery-service
    ports:
    - 8761:8761
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
    links:
    - config-service
  admin-service:
    image: davimonteiro/admin-service
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
    - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    ports:
    - 9191:9191
    links:
    - discovery-service
  beethoven-service:
    image: davimonteiro/beethoven-service
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
    ports:
    - 9090:9090
    links:
    - discovery-service
  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=dbpass
    - MYSQL_DATABASE=dev
  user-service:
    image: davimonteiro/user-service
    ports:
    - 8181:8181
    links:
    - mysql
    - discovery-service
    - config-service
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
  edge-service:
    image: davimonteiro/edge-service
    ports:
    - 9999:9999
    links:
    - user-service
    - discovery-service
    - config-service
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
  account-service:
    image: davimonteiro/account-service
    links:
    - user-service
    - discovery-service
    - config-service
    - mysql
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
  inventory-service:
    image: davimonteiro/inventory-service
    links:
    - mysql
    - discovery-service
    - config-service
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
  order-service:
    image: davimonteiro/order-service
    links:
    - mysql
    - discovery-service
    - config-service
    - user-service
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
  catalog-service:
    image: davimonteiro/catalog-service
    links:
    - mysql
    - discovery-service
    - config-service
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
  shopping-cart-service:
    image: davimonteiro/shopping-cart-service
    links:
    - mysql
    - discovery-service
    - config-service
    - user-service
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP
  online-store-web:
    image: davimonteiro/online-store-web
    ports:
    - 8787:8787
    links:
    - discovery-service
    - config-service
    - user-service
    - edge-service
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DOCKER_IP=$DOCKER_IP